### ISSUE TITLE
Upgrading to Keycloak v17/18+

### ISSUE THREAD

**Issue by XcrigX** [Alvearie/keycloak-extensions-for-fhir#64]
The current project is fixed to Keycloak 16.1.1. 
It appears starting with Keycloak 17, significant changes have been made to how keycloak configuration works: 
https://www.keycloak.org/docs/latest/release_notes/index.html#keycloak-17-0-0

_"The default Keycloak distribution is now based on Quarkus. The new distribution is faster, leaner, and a lot easier to configure!
We appreciate migrating from the WildFly distribution is not going to be straightforward for everyone, since how you start and configure Keycloak has radically changed. With that in mind we will continue to support the WildFly distribution until June 2022."_

Note also the end support date of June 2022. 

Are the maintainers here planning an update, or should your (very appreciative) users plan this on their own? 
Thanks!

NOTE: I haven't tried or looked deeply into the changes or upgrading as of yet, but will share back anything I learn or do here.

**Comment by lmsurpre** [comment]
I don't have immediate plans for looking into the Quarkus distribution...any insights you (or others) can provide on the changes required for that would be most welcome.

**Comment by lmsurpre** [comment]
For cases where a user has access to more than one patient and a `launch/patient` scope is requested, the current implementation makes use IBM FHIR Server client libs (packaged as a jboss module)...I don't think any of that will work in Quarkus.  I'd probably start by looking at version 2.x of the `testcontainers-keycloak` project which supports the Quarkus-based keycloak distribution...hopefully that could provide a nice environment to iterate on client.

Also, if its needed, feel free to open an issue at IBM/FHIR to request quarkus support from the main libs (fhir-model and fhir-provider) there.

**Comment by XcrigX** [comment]
@lmsurpre -  We had some luck getting this to work on the Quarkus version. We used the HAPI client libs rather than Jboss to query the FHIR server and packaged the custom authenticator as a shaded/uber jar which can then be deployed with Keycloak at a specific path.
One difference to be aware of is this guidance in the 17.x release notes:
"With the new distribution there is no longer a separate classpath for custom providers, so you may need to be more careful with what additional dependencies you include. In addition, the EAR packaging format, and jboss-deployment-structure.xml files, is no longer supported."

There are of course a lot of differences in how to configure and run Keycloak in the latest version as well.

I hope to share this back when we get to a stable point, but wanted to update that it's possible and not too difficult or different really from what you had.

**Comment by jigneshmpatel** [comment]
@XcrigX do you able to make any progress of using keycloak based on quarkus? I am seeing there are many branches created from @lmsurpre. Is there any branch we can pick up and start working on it, if required we can also work towards completing pending task.

**Comment by XcrigX** [comment]
@jigneshmpatel - I have my working copy here: https://github.com/xcrigx/keycloak-extensions-for-fhir/tree/feature/quarkus-update
I'm still working through some issues with the unit tests so I haven't pushed it to this repo yet. There is also some work to do to update the readme. I'll update here when I get it fully functioning - I think it's 95% there. 
@lmsurpre - Let me know how you'd like to handle it when it's working - a separate branch here?

**Comment by jigneshmpatel** [comment]
@XcrigX thank you for response. Since the window of certification of g10 is very close, how do we jump in and start working. Is it only test cases are not working?

**Comment by XcrigX** [comment]
Some context: I have everything working in a different/private repo we had started from scratch using this project as a guide. 
I am now trying to port what we did back to this project. So I know it _can_ work. 
I have not tested this version out 'live' yet though. I just started porting it back here today. 

I'm down to one strange test failure. The KeyCloakConfig.PropertyGroupTest fails when running from command line, but works in Eclipse. I'm out of time to figure it out today though.. 

Feel free to grab it and build it. Keycloak does come up. 

Be warned - I found Keycloak to be tricky to get configured to run in real environment (behind a reverse-proxy, admin console not publicly available, TLS, etc.). 
The Dockerfile here is starting the server in dev mode. You'll need to change all that to run it "for real". 
See: https://www.keycloak.org/guides for more info.

**Comment by jigneshmpatel** [comment]
ok see if there is a progress being made towards the end of week, we will start exploring about sometime early next week.

**Comment by XcrigX** [comment]
fyi, unit test errors all fixed now - was just an issue with the surefire plugin version and junit5

**Comment by XcrigX** [comment]
NOTE: I deleted and recreated the branch also so I could squash everything into 1 commit: https://github.com/XcrigX/keycloak-extensions-for-fhir/tree/quarkus-update

**Comment by lmsurpre** [comment]
Thats awesome @XcrigX ... please open a PR if you're interested in contributing that.
We do follow [DCO](https://github.com/Alvearie/keycloak-extensions-for-fhir/blob/main/CONTRIBUTING.md#developers-certificate-of-origin) here and so you'd need to amend your commit to add a single-line signoff.

**Comment by jigneshmpatel** [comment]
That is awesome so @XcrigX <https://github.com/XcrigX> this branch code
does not require any mocifcations?
https://github.com/XcrigX/keycloak-extensions-for-fhir/tree/quarkus-update

**Comment by XcrigX** [comment]
pushed another update to fix some docker build issues and update the readme to reflect proper docker build commands and paths.  @jigneshmpatel  - I haven't run it through the ringer yet to functionally test it and I may not get to that right now. The images build and come up. The code should not require any modifications unless there are bugs/issues - however you will need to make your own Dockerfile if you intend to deploy it in a non-test environment. You'll need to fill in various env variables to the container for your environment (database, hostnames, etc.) , and you'd want to start keycloak NOT in dev mode.

**Comment by jigneshmpatel** [comment]
got it.

**Comment by jigneshmpatel** [comment]
are there build steps I can follow?
I believe I need to checkout the branch: keycloak-extensions-for-fhir

**Comment by jigneshmpatel** [comment]
I could able to compile on jdk17 using
mvn -B clean package -DskipTests

**Comment by jigneshmpatel** [comment]
I am not able to run
docker run -v <My_PATH>:/config -e KEYCLOAK_BASE_URL=http://localhost:8081/auth alvearie/keycloak-config -configFile config/keycloak-config.json

**Comment by jigneshmpatel** [comment]
Seems is it because of JDK17?

**Comment by jigneshmpatel** [comment]
My team member able to bring up the server in main branch but as stated above I can't run the feature/quarkus-update branch.

**Comment by XcrigX** [comment]
@jigneshmpatel  - Be sure to check that you are connected to the proper branch - I deleted and recreated it a couple of times. 
I updated the readme.md documentation to update the environment variable names and things - but possible I still missed something. 

You could also access the code from the PR I submitted: 
https://github.com/Alvearie/keycloak-extensions-for-fhir/pull/97

Once you've verified you have the latest updates from the proper branch, these commands I think should work to start it: 

docker build . -f keycloak-config/Dockerfile -t alvearie/keycloak-config

docker run -v /local/config/dir:/config -e KEYCLOAK_BASE_URL=http://host.docker.internal:8080 alvearie/keycloak-config -configFile config/keycloak-config.json


You'd then need to build and run the keycloakConfig container as well once that is working to create the test realm with SMART support.

**Comment by XcrigX** [comment]
apologies, I gave the keycloak config info above.. The smart keycloak command would be: 

docker run -p 8080:8080 -p 8443:8443 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin alvearie/smart-keycloak

**Comment by jigneshmpatel** [comment]
Is it advisable to run with JDK 17? As it has a long term support.

**Comment by jigneshmpatel** [comment]
We need some guidance
How to configure following:
keycloak
"capabilities": [
        "launch-ehr",
        "launch-standalone",
        "client-public",
        "client-confidential-symmetric",
        "sso-openid-connect",
        "context-banner",
        "context-style",
        "context-ehr-patient",
        "context-ehr-encounter",
        "context-standalone-patient",
        "context-standalone-encounter",
        "permission-offline",
        "permission-patient",
        "permission-user"
    ]
    
    management_endpoint
also in response we are not able to set header values

**Comment by jigneshmpatel** [comment]
@XcrigX 
I have run the command you mentioned. But I am not able to see following auth flow.
<img width="978" alt="Screen Shot 2022-10-30 at 8 16 12 PM" src="https://user-images.githubusercontent.com/780048/198909036-0addd29e-2f9c-4074-992a-46a876a73bd6.png">

**Comment by jigneshmpatel** [comment]
I am seeing following error

`00:43:53,454 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-7) WFLYELY01084: KeyStore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self-signed certificate for host localhost
00:43:53,468 INFO  [org.jboss.modcluster] (ServerService Thread Pool -- 58) MODCLUSTER000001: Initializing mod_cluster version 1.4.3.Final
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/opt/jboss/keycloak/modules/system/layers/base/org/wildfly/extension/elytron/main/wildfly-elytron-integration-15.0.1.Final.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()
WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
00:43:53,591 ERROR [org.jboss.modcluster] (ServerService Thread Pool -- 58) MODCLUSTER000034: Failed to start advertise listener: java.net.SocketException: Protocol not available (Error setting socket option)
	at java.base/java.net.PlainDatagramSocketImpl.socketSetOption0(Native Method)
	at java.base/java.net.PlainDatagramSocketImpl.socketSetOption(PlainDatagramSocketImpl.java:91)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.setOption(AbstractPlainDatagramSocketImpl.java:352)
	at java.base/java.net.MulticastSocket.setInterface(MulticastSocket.java:477)
	at org.jboss.mod_cluster.core@1.4.3.Final//org.jboss.modcluster.advertise.impl.AdvertiseListenerImpl.init(AdvertiseListenerImpl.java:151)
	at org.jboss.mod_cluster.core@1.4.3.Final//org.jboss.modcluster.advertise.impl.AdvertiseListenerImpl.start(AdvertiseListenerImpl.java:161)
	at org.jboss.mod_cluster.core@1.4.3.Final//org.jboss.modcluster.ModClusterService.init(ModClusterService.java:166)
	at org.wildfly.mod_cluster.undertow@23.0.2.Final//org.wildfly.mod_cluster.undertow.UndertowEventHandlerAdapterService.start(UndertowEventHandlerAdapterService.java:83)
	at org.wildfly.clustering.service@23.0.2.Final//org.wildfly.clustering.service.AsyncServiceConfigurator$AsyncService.lambda$start$0(AsyncServiceConfigurator.java:117)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)

00:43:54,467 INFO  [org.jboss.as.ejb3] (MSC service thread 1-4) WFLYEJB0493: Jakarta Enterprise Beans subsystem suspension complete
00:43:55,573 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-8) WFLYJCA0001: Bound data source [java:jboss/datasources/KeycloakDS]
00:43:55,573 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-5) WFLYJCA0001: Bound data source [java:jboss/datasources/ExampleDS]
00:43:56,140 INFO  [org.jboss.as.patching] (MSC service thread 1-4) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
00:43:56,228 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-1) WFLYDM0111: Keystore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
00:43:56,276 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-6) WFLYDS0013: Started FileSystemDeploymentService for directory /opt/jboss/keycloak/standalone/deployments
00:43:56,336 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0027: Starting deployment of "keycloak-server.war" (runtime-name: "keycloak-server.war")
00:43:56,336 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0027: Starting deployment of "keycloak-extensions-0.0.1-SNAPSHOT.jar" (runtime-name: "keycloak-extensions-0.0.1-SNAPSHOT.jar")
00:43:56,505 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0006: Undertow HTTPS listener https listening on 0.0.0.0:8443
00:43:58,457 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-5) WFLYSRV0018: Deployment "deployment.keycloak-extensions-0.0.1-SNAPSHOT.jar" is using a private module ("org.keycloak.keycloak-services") which may be changed or removed in future versions without notice.
00:43:58,540 INFO  [org.keycloak.subsystem.server.extension.KeycloakProviderDeploymentProcessor] (MSC service thread 1-5) Deploying Keycloak provider: keycloak-extensions-0.0.1-SNAPSHOT.jar
00:44:00,272 ERROR [org.jgroups.protocols.UDP] (ServerService Thread Pool -- 58) failed setting interface to /172.17.0.2: java.net.SocketException: Protocol not available (Error setting socket option)
00:44:00,282 ERROR [org.jgroups.protocols.UDP] (ServerService Thread Pool -- 58) failed setting interface to /172.17.0.2: java.net.SocketException: Protocol not available (Error setting socket option)
00:44:00,287 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 58) MSC000001: Failed to start service org.wildfly.clustering.jgroups.channel.ee: org.jboss.msc.service.StartException in service org.wildfly.clustering.jgroups.channel.ee: java.lang.IllegalStateException: java.net.SocketException: Protocol not available
	at org.wildfly.clustering.service@23.0.2.Final//org.wildfly.clustering.service.FunctionalService.start(FunctionalService.java:66)
	at org.wildfly.clustering.service@23.0.2.Final//org.wildfly.clustering.service.AsyncServiceConfigurator$AsyncService.lambda$start$0(AsyncServiceConfigurator.java:117)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: java.lang.IllegalStateException: java.net.SocketException: Protocol not available
	at org.jboss.as.clustering.jgroups@23.0.2.Final//org.jboss.as.clustering.jgroups.subsystem.ChannelServiceConfigurator.get(ChannelServiceConfigurator.java:116)
	at org.jboss.as.clustering.jgroups@23.0.2.Final//org.jboss.as.clustering.jgroups.subsystem.ChannelServiceConfigurator.get(ChannelServiceConfigurator.java:58)
	at org.wildfly.clustering.service@23.0.2.Final//org.wildfly.clustering.service.FunctionalService.start(FunctionalService.java:63)
	... 7 more
Caused by: java.net.SocketException: Protocol not available
	at java.base/java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:216)
	at java.base/java.net.MulticastSocket.joinGroup(MulticastSocket.java:328)
	at org.jgroups@4.2.11.Final//org.jgroups.protocols.UDP.createSockets(UDP.java:417)
	at org.jgroups@4.2.11.Final//org.jgroups.protocols.UDP.start(UDP.java:292)
	at org.jgroups@4.2.11.Final//org.jgroups.stack.ProtocolStack.startStack(ProtocolStack.java:881)
	at org.jgroups@4.2.11.Final//org.jgroups.JChannel.startStack(JChannel.java:989)
	at org.jgroups@4.2.11.Final//org.jgroups.JChannel._preConnect(JChannel.java:853)
	at org.jgroups@4.2.11.Final//org.jgroups.JChannel.connect(JChannel.java:358)
	at org.jgroups@4.2.11.Final//org.jgroups.JChannel.connect(JChannel.java:352)
	at org.jboss.as.clustering.jgroups@23.0.2.Final//org.jboss.as.clustering.jgroups.subsystem.ChannelServiceConfigurator.get(ChannelServiceConfigurator.java:112)
	... 9 more

00:44:00,699 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "jgroups"),
    ("channel" => "ee")
]) - failure description: {"WFLYCTL0080: Failed services" => {"org.wildfly.clustering.jgroups.channel.ee" => "java.lang.IllegalStateException: java.net.SocketException: Protocol not available
    Caused by: java.lang.IllegalStateException: java.net.SocketException: Protocol not available
    Caused by: java.net.SocketException: Protocol not available"}}
00:44:00,745 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 46) WFLYSRV0010: Deployed "keycloak-server.war" (runtime-name : "keycloak-server.war")
00:44:00,743 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 34) WFLYSRV0010: Deployed "keycloak-extensions-0.0.1-SNAPSHOT.jar" (runtime-name : "keycloak-extensions-0.0.1-SNAPSHOT.jar")
00:44:00,755 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service org.wildfly.clustering.jgroups.channel.ee: java.lang.IllegalStateException: java.net.SocketException: Protocol not available
WFLYCTL0448: 43 additional services are down due to their dependencies being missing or failed
00:44:01,085 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
00:44:01,100 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: Keycloak 15.0.2 (WildFly Core 15.0.1.Final) started (with errors) in 24833ms - Started 538 of 974 services (50 services failed or missing dependencies, 686 services are lazy, passive or on-demand)
00:44:01,107 INFO  [org.jboss.as] (Controller Boot Thread) WFLYS`

**Comment by jigneshmpatel** [comment]
If you guys provide some guidance and give us headstart, we should be able to give back to community based on what we learn.
